# Generated by Django 3.2.7 on 2023-01-15 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('ci', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'candidates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Techs',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'techs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateTechs',
            fields=[
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.candidates')),
                ('years', models.IntegerField()),
            ],
            options={
                'db_table': 'candidate_techs',
                'managed': False,
            },
        ),
    ]
