# Generated by Django 3.2.7 on 2023-01-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidates',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='candidatetechs',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='techs',
            options={'managed': True},
        ),
    ]
