# Generated by Django 3.2.7 on 2023-01-15 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230115_0129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatetechs',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='candidates',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='techs',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
